version: '2'
services:
  db:
    env_file: db.env
    image: postgres
  web:
    build: .
    command: foreman start -f Procfile.dev
    depends_on:
      - db
    env_file:
      - db.env
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/tmp
  test:
    build: .
    command: bundle exec rspec --format progress --format RspecJunitFormatter -o rspec.xml
    depends_on:
      - db
    env_file:
      - db.env
    volumes:
      - .:/src
