version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Examine tools
          command: |
            which docker && docker version
            which docker-compose && docker-compose version
            which make && make --version
            pwd && ls -la
#      - run: mkdir -p /tmp/test-reports
#      - run: bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/test-reports/rspec.xml
#      - store_test_results:
#          path: /tmp/test-reports
