version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    working_directory: /build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Examine docker
          command: |
            docker version
      - run:
          name: Examine docker-compose
          command: |
            docker-compose version
      - run:
          name: Examine make
          command: |
            make --version
      - run:
          name: Build image locally
          command: |
            make image
      - run:
          name: Prepare test environment
          command: |
            make prep
      - run:
          name: Test
          command: |
            mkdir -p reports/rspec
            docker-compose run test bash -c "bundle exec rspec --format progress --format RspecJunitFormatter -o reports/rspec/rspec.xml"
      - store_test_results:
          path: reports
