version: 2
jobs:
  build:
    machine: true
    working_directory: ~/src
    steps:
      - checkout
      - run:
          name: Examine docker
          command: |
            docker version
      - run:
          name: Examine docker-compose
          command: |
            docker-compose version
      - run:
          name: Examine make
          command: |
            make --version
      - run:
          name: Build image locally
          command: |
            make image
      - run:
          name: Prepare tests
          command: |
            pwd && ls -la
            cat docker-compose.yml
            make prep
      - run:
          name: Test
          command: |
            mkdir -p reports/rspec
            pwd && ls -la
            cat docker-compose.yml
            docker-compose run test bash -c "bundle exec rspec --format progress --format RspecJunitFormatter -o reports/rspec/rspec.xml"
      - store_test_results:
          path: reports
