version: 2
jobs:
  build:
    docker:
     - image: vidbina/ror-react-base:alpha
    working_directory: /build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
#      - run: mkdir -p /tmp/test-reports
#      - run: bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/test-reports/rspec.xml
#      - store_test_results:
#          path: /tmp/test-reports
