/* eslint-disable import/prefer-default-export */

export const HELLO_WORLD_NAME_UPDATE = 'HELLO_WORLD_NAME_UPDATE';
export const HELLO_WORLD_PASSWORD_UPDATE = 'HELLO_WORLD_PASSWORD_UPDATE';

export const SHOW_LOGIN_PROMPT = 'SHOW_LOGIN_PROMPT';
export const HIDE_LOGIN_PROMPT = 'HIDE_LOGIN_PROMPT';

export const SHOW_DEBUG_DRAWER = 'SHOW_DEBUG_DRAWER';
export const HIDE_DEBUG_DRAWER = 'HIDE_DEBUG_DRAWER';
